### DISCUSSION TITLE
Target State of Charge / Charge Limit

### DISCUSSION THREAD

**Discussion by T1ppes** [ngocjohn/vehicle-status-card#121] [Ideas]
My EV provides the Target State of Charge as a sensor and number entity.

1. It would be great if the target state of charge value could be displayed in the range progress bar.
2. Furthermore it would be great if a tap on the range progress bar would take me to the number entity, in order to set the target state of charge.

**Comment by ngocjohn** [comment]
Hi @T1ppes, In the last version tap action options for range info entities were added. Give it a try and let us know how you like it.

**Reply by T1ppes** [reply]
Thanks for the effort. I can see that a tap action can now be defined to for example increment the number entity, when tapping on the range bar (e.g. number.cupra_born_target_state_of_charge), but I was more hoping on something like the button cards, which would when tapping on the range bar open a pop up number card. Something like this:
![Bildschirmfoto 2025-06-04 um 09 07 47](https://github.com/user-attachments/assets/88661d2b-5918-4626-9681-86548f63ffdc)
If this is possible with the newly introduced option, could you let me know how to implement it?

**Reply by ngocjohn** [reply]
> If this is possible with the newly introduced option, could you let me know how to implement it?

Hi, you can use the browser mod and create a popup card, something like that 
```
energy_level:
  entity: sensor.6z1_2359_state_of_charge
  icon: mdi:battery-30
  hold_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        title: Button
        content:
          type: entities
          entities:
            - button.push
```
![2025-06-04 21 35 01](https://github.com/user-attachments/assets/ba4d97d3-d644-4b9b-a050-730f86274dcb)
