### ISSUE TITLE
[Bug] Single Map Card, re-center doesn't work as expected

### ISSUE THREAD

**Issue by Duncan1106** [ngocjohn/vehicle-status-card#112]
### Short summary 📝

The re-center button doesn't jump to the current location of the device_tracker. 

### Detailed description 📋

The map shows the home zone, even if the zone.home isn't configured.
When the device_trackers real location is visible again if zoomed out enough, then the center button jumps to it correctly.

Here's the map config part:

```
mini_map:
  device_tracker: device_tracker.vw_id4_location
  maptiler_api_key: abcdefgh
  single_map_card: true
  hours_to_show: 24
  auto_fit: true
  fit_zones: true
  map_styles:
    dark: HYBRID
```

### Version 📦

v1.11.0
