### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by PurelyNicole** [ngocjohn/vehicle-status-card#129]
### Short summary 📝

Vehicle card no longer shows in version 1.12.0

### Detailed description 📋

My vehicle card is configured as follows on Home Assistant 2025.5.3:

```yaml
type: custom:vehicle-status-card
button_card:
  - button:
      primary: Remote Start
      secondary:
        - entity: ""
          attribute: ""
          state_template: ""
      icon: mdi:car-wireless
      notify: ""
    button_type: action
    hide_button: false
    card_type: default
    default_card: []
    custom_card: []
    button_action:
      entity: button.cooper_se_activate_air_conditioning
      tap_action:
        action: perform-action
        perform_action: button.press
        target:
          entity_id: button.cooper_se_activate_air_conditioning
      hold_action:
        action: none
      double_tap_action:
        action: none
  - button:
      icon: mdi:lock
      primary: Lock Car
      secondary:
        entity: ""
        attribute: ""
        state_template: ""
    button_type: action
    hide_button: false
    card_type: default
    default_card: []
    custom_card: []
    button_action:
      entity: lock.cooper_se_lock
      tap_action:
        action: perform-action
        perform_action: button.press
        target:
          entity_id: button.cooper_se_activate_air_conditioning
      hold_action:
        action: none
      double_tap_action:
        action: none
layout_config:
  button_grid:
    rows: 2
    columns: 2
    swipe: true
  hide:
    button_notify: false
    buttons: false
    images: false
    indicators: false
    mini_map: false
    range_info: false
    map_address: false
  theme_config:
    mode: auto
    theme: default
  section_order:
    - header_info
    - images
    - mini_map
    - buttons
name: Mini SE
mini_map:
  device_tracker: device_tracker.cooper_se
  enable_popup: true
  us_format: true
indicators:
  single:
    - entity: binary_sensor.cooper_se_check_control_messages
      icon: ""
      attribute: ""
      action_config:
        entity: binary_sensor.cooper_se_check_control_messages
        tap_action:
          action: more-info
        hold_action:
          action: none
        double_tap_action:
          action: none
    - entity: binary_sensor.cooper_se_connection_status
      icon: ""
      attribute: ""
      action_config:
        entity: binary_sensor.cooper_se_connection_status
        tap_action:
          action: more-info
        hold_action:
          action: none
        double_tap_action:
          action: none
    - entity: lock.cooper_se_lock
      icon: ""
      attribute: ""
      action_config:
        entity: lock.cooper_se_lock
        tap_action:
          action: more-info
        hold_action:
          action: none
        double_tap_action:
          action: none
    - entity: binary_sensor.cooper_se_windows
      icon: ""
      attribute: ""
      action_config:
        entity: binary_sensor.cooper_se_windows
        tap_action:
          action: more-info
        hold_action:
          action: none
        double_tap_action:
          action: none
    - entity: sensor.cooper_se_mileage
      icon: ""
      attribute: ""
      action_config:
        entity: sensor.cooper_se_mileage
        tap_action:
          action: more-info
        hold_action:
          action: none
        double_tap_action:
          action: none
range_info:
  - energy_level:
      entity: sensor.cooper_se_charging_level_hv
      attribute: ""
      icon: ""
    range_level:
      entity: sensor.cooper_se_remaining_range_electric
      attribute: ""
    progress_color: "#004225"
    charging_entity: sensor.cooper_se_charging_status
images:
  - url: /api/image/serve/8ff59364976234fdf98ce0ef19547e89/original
    title: MINI_SE.PNG
```

This configuration works in 1.11.3, in version 1.12.0 the card does not display. Also, if trying to add a new Vehicle Status Card, visual editor goes blank upon adding an indicator.

### Version 📦

v1.12.0

### Environment 🌐

Chrome Windows 11, Edge Windows 11, Firefox Windows 11, Offical App on iOS

### Logs and screenshots 📂

This is the error displayed in the Chrome developer console:

```
vehicle-status-card.js?hacstag=8593716631120:4294 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Rz._renderIndicators (vehicle-status-card.js?hacstag=8593716631120:4294:97)
    at vehicle-status-card.js?hacstag=8593716631120:4292:22
    at Array.map (<anonymous>)
    at Rz._renderMainCard (vehicle-status-card.js?hacstag=8593716631120:4291:11)
    at Rz.render (vehicle-status-card.js?hacstag=8593716631120:4288:45)
    at Rz.update (vehicle-status-card.js?hacstag=8593716631120:22:256)
    at Rz.performUpdate (vehicle-status-card.js?hacstag=8593716631120:11:4621)
    at Rz.scheduleUpdate (vehicle-status-card.js?hacstag=8593716631120:11:4139)
    at Rz._$EP (vehicle-status-card.js?hacstag=8593716631120:11:4047)
_renderIndicators @ vehicle-status-card.js?hacstag=8593716631120:4294
(anonymous) @ vehicle-status-card.js?hacstag=8593716631120:4292
_renderMainCard @ vehicle-status-card.js?hacstag=8593716631120:4291
render @ vehicle-status-card.js?hacstag=8593716631120:4288
update @ vehicle-status-card.js?hacstag=8593716631120:22
performUpdate @ vehicle-status-card.js?hacstag=8593716631120:11
scheduleUpdate @ vehicle-status-card.js?hacstag=8593716631120:11
_$EP @ vehicle-status-card.js?hacstag=8593716631120:11
await in _$EP
requestUpdate @ vehicle-status-card.js?hacstag=8593716631120:11
set @ vehicle-status-card.js?hacstag=8593716631120:11
set hass @ vehicle-status-card.js?hacstag=8593716631120:4283
update @ hui-card.ts:191
performUpdate @ reactive-element.ts:1503
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
(anonymous) @ hui-section.ts:132
update @ hui-section.ts:131
performUpdate @ reactive-element.ts:1503
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
(anonymous) @ hui-view.ts:266
update @ hui-view.ts:264
performUpdate @ reactive-element.ts:1503
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
updated @ hui-root.ts:524
_$AE @ reactive-element.ts:1552
performUpdate @ reactive-element.ts:1517
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
j @ lit-html.ts:1983
_$AI @ lit-html.ts:1923
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
j @ lit-html.ts:2274
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1503
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
updatePageEl @ partial-panel-resolver.ts:97
update @ hass-router-page.ts:89
performUpdate @ reactive-element.ts:1503
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
j @ lit-html.ts:1983
_$AI @ lit-html.ts:1923
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
j @ lit-html.ts:2274
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1503
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
j @ lit-html.ts:1983
_$AI @ lit-html.ts:1923
p @ lit-html.ts:1282
$ @ lit-html.ts:1636
_$AI @ lit-html.ts:1475
j @ lit-html.ts:2274
update @ lit-element.ts:171
performUpdate @ reactive-element.ts:1503
t.performUpdate @ storage.ts:172
scheduleUpdate @ reactive-element.ts:1399
_$EP @ reactive-element.ts:1371
await in _$EP
requestUpdate @ reactive-element.ts:1310
set @ reactive-element.ts:789
_updateHass @ hass-base-mixin.ts:50
_updateHass @ context-mixin.ts:107
(anonymous) @ connection-mixin.ts:235
n @ store.js:19
(anonymous) @ entities.js:74
(anonymous) @ entities.js:76
(anonymous) @ connection.js:23
_handleMessage @ connection.js:15
```
