### ISSUE TITLE
[Feature] Use !secret for both possible API Keys

### ISSUE THREAD

**Issue by Duncan1106** [ngocjohn/vehicle-status-card#135]
### Short summary

It would be great to make it possible to use the !secret functions for the api keys

### Detailed description

```
mini_map:
  device_tracker: device_tracker.id4
  enable_popup: true
  hours_to_show: 24
  theme_mode: auto
  default_zoom: 16
  google_api_key: !secret google_maps_api_key
  maptiler_api_key: !secret maptiler_api_key
  auto_fit: true
  use_zone_name: true
```

something like this would be great
