### ISSUE TITLE
[Bug] adding range and batter info doesnt work

### ISSUE THREAD

**Issue by blair287** [ngocjohn/vehicle-status-card#38]
### Short summary 📝

Adding range and battery entities once saved they disappear and never show up

### Detailed description 📋

Adding the range progress bar added the battery and range entities click save and the card never changes and opening the editor again they have disappeared.

Working fine on another HA install this is a for a friend and just cannot get the card work work.

### Version 📦

v1.4.0

### Logs and screenshots 📂

![20241205_141152](https://github.com/user-attachments/assets/db3a272c-4490-4ddc-ab3c-7217b133d33f)
Added the entities then
![20241205_141209](https://github.com/user-attachments/assets/5e3a338b-7b19-49f4-b391-0ae6484dc005)
All gone card never changes.

**Comment by blair287** [comment]
Downgrading to 1.3.1 Adding the range info bar worked then updating to 1.4 was all OK still

**Comment by ngocjohn** [comment]
Hi @blair287 , yes there was a small change in the range config. Is it ok in the new version?

**Comment by blair287** [comment]
> Hi @blair287 , yes there was a small change in the range config. Is it ok in the new version?

I can't edit it in 1.4 for some reason can only edit in 1.3

**Comment by ngocjohn** [comment]
@blair287 Can you copy your config for the range part? I don't remember changing anything in the new version. 😅

**Comment by nikee73** [comment]
Same here. Updated from 1.3.1 to 1.4.1 and Range progress bar disappeared

**Comment by nikee73** [comment]
@ngocjohn do you mean this?
range_info:
  - energy_level:
      - entity: sensor.battery_level
        icon: mdi:battery
    range_level:
      - entity: sensor.battery_range
        attribute: ""
    progress_color: ""

**Comment by ngocjohn** [comment]
> * energy_level:
>   
>   * entity: sensor.battery_level
>     icon: mdi:battery
>     range_level:
>   * entity: sensor.battery_range
>     attribute: ""
>     progress_color: ""

Do you have the card in the latest version? v1.4.2. I had a small bug in the configuration, but I added a function to auto fix, the editor should assign the array correctly. It doesn't seem to be working 🥲 Anyway, please edit to this configuration, it will work again and the new config will be saved. 
```yaml
- energy_level:
    entity: sensor. battery_level
    attribute: ""
    icon: mdi:battery
  range_level:
    entity: sensor. battery_range
    attribute: ""
  progress_color: ""
```
![CleanShot 2024-12-11 at 18 06 54@2x](https://github.com/user-attachments/assets/1caa09fb-e8db-4b36-978d-01240f6f91ac)

**Comment by nikee73** [comment]
@ngocjohn this was on 1.3.0 as that was to only one working

**Comment by ngocjohn** [comment]
@nikee73 Yes, the config for range was set differently in v1.3.0. It was causing a problem when adding another range bar. If you have a new version, you have to edit to the new configuration see above, try it and let me know..

**Comment by ngocjohn** [comment]
this is the old config:
```yaml
- energy_level: 
    - entity: sensor.battery_level #wrong
      icon: mdi:battery
      range_level:
    - entity: sensor.battery_range #wrong 
      attribute: ""
      progress_color: ""
```
this is the new config: 
```yaml
- energy_level:
    entity: sensor. battery_level
    attribute: ""
    icon: mdi:battery
  range_level:
    entity: sensor. battery_range
    attribute: ""
  progress_color: ""
```
