### ISSUE TITLE
[Bug] Range bar does not appear to consistently save in UI, and also requires both energy_level and range_level to be set to appear, should not require range_level

### ISSUE THREAD

**Issue by mitman98** [ngocjohn/vehicle-status-card#94]
### Short summary 📝

I've found that the range bar will not save changes when I edit it in the UI often. More importantly for me, you have to have value set for both energy_level and range_level for the bar to appear, should not require range_level.

### Detailed description 📋

I've found that the range bar will not save changes when I edit it in the UI often. I have to go to the code editor (where I see all empty quotes for values) to actually set values. For me this seems to be pretty consistent every time I create a new bar.

More importantly for me, you have to have value set for both energy_level and range_level for the bar to appear. However, not all my bars have both. I have a vehicle where i only have fuel level %, but no range information. I still want to have a bar showing the fuel level. I should not be required to have to have range_level as I view that as optional information that shows to the right of the bar that should not be required. Can you remove that requirement to show the bar?

For now I just duplicate and put the energy_level value for fuel % into the range_level also to get the bar to appear which is fine, but it shows the same number on the left and right of the bar. So ideally just don't require range_level.

### Version 📦

v1.8.3-beta.2

**Comment by ngocjohn** [comment]
Hi @mitman98, I see that some users have a problem with the range info bars. I'll try to rewrite a completely new configuration method for this function to prevent these problems in the future. I'll let you know when it's ready.  

ps. Can you send the yaml config for this part from your configuration?

**Comment by mitman98** [comment]
Sure! here's the config section:

```
range_info:
  - energy_level:
      entity: sensor.2020_jeep_gladiator_car_fuel
      attribute: ""
      icon: ""
    range_level:
      entity: sensor.2020_jeep_gladiator_car_fuel
      attribute: ""
    progress_color: "#d5bf0d"
    charging_entity: ""
```
